"""created published field to match

Revision ID: 16af3ce5288e
Revises: c2c1aae88108
Create Date: 2021-01-08 10:38:06.890862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16af3ce5288e'
down_revision = 'c2c1aae88108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'published')
    # ### end Alembic commands ###
