"""updated country model

Revision ID: 181c0d6ac9b6
Revises: 79188ac654ca
Create Date: 2021-01-07 18:29:21.638228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181c0d6ac9b6'
down_revision = '79188ac654ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'short',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('country', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'country', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.alter_column('country', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('country', 'short',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
