"""Init project

Revision ID: 7ed911eb735b
Revises: 
Create Date: 2021-01-05 22:53:53.120557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed911eb735b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'match', ['id'])
    op.create_unique_constraint(None, 'team', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_constraint(None, 'match', type_='unique')
    # ### end Alembic commands ###
