"""Added played_at to match model

Revision ID: 8974e0fbb97c
Revises: 19e4dbb960df
Create Date: 2021-01-07 16:14:08.522874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8974e0fbb97c'
down_revision = '19e4dbb960df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    op.add_column('match', sa.Column('played_at', sa.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'match', ['id'])
    op.create_unique_constraint(None, 'team', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_constraint(None, 'match', type_='unique')
    op.drop_column('match', 'played_at')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
