"""updated models

Revision ID: c2c1aae88108
Revises: ffe4270c2bcb
Create Date: 2021-01-07 19:20:00.516472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c1aae88108'
down_revision = 'ffe4270c2bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'type')
    op.create_unique_constraint(None, 'match_kind', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_kind', type_='unique')
    op.add_column('match', sa.Column('type', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
